# Caramel AI Development Environment
# Full stack compose file with dev container, Postgres, and Redis
#
# Usage:
#   ./start-dev.sh [branch-name]    - Recommended launcher script
#   docker compose -f compose.dev.yaml up -d pgsql redis  - Start dependencies only
#   docker compose -f compose.dev.yaml down               - Stop all services

services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: caramel-dev:latest
    container_name: caramel-dev
    volumes:
      # Mount git config for identity
      - ~/.gitconfig:/home/developer/.gitconfig:ro
      # Mount SSH keys for git operations (read-only)
      - ~/.ssh:/home/developer/.ssh:ro
      # Persist OpenCode data (auth, history, etc.)
      - opencode-data:/home/developer/.local/share/opencode
    environment:
      - BRANCH
      - ASPNETCORE_ENVIRONMENT=Development
      # Database - standardized configuration names
      - CARAMEL_DATABASE_CONNECTIONSTRING=Host=pgsql;Database=caramel_db;Username=caramel;Password=caramel
      - CARAMEL_QUARTZ_CONNECTIONSTRING=Host=pgsql;Database=caramel_db;Username=caramel;Password=caramel
      # Redis - standardized configuration names
      - CARAMEL_REDIS_CONNECTIONSTRING=redis:6379,password=caramel_redis
      # gRPC config - standardized configuration names
      - CARAMEL_GRPC_HOST=caramel-service
      - CARAMEL_GRPC_PORT=5270
      - CARAMEL_GRPC_USEHTTPS=false
      - CARAMEL_GRPC_VALIDATESSLCERTIFICATE=false
    stdin_open: true
    tty: true
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - caramel

  pgsql:
    image: postgres:16
    container_name: caramel-pgsql
    environment:
      POSTGRES_USER: caramel
      POSTGRES_PASSWORD: caramel
      POSTGRES_DB: caramel_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caramel -d caramel_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - caramel

  redis:
    image: redis:7
    container_name: caramel-redis
    command: redis-server --requirepass caramel_redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - caramel

volumes:
  postgres-data:
    name: caramel-postgres-data
  redis-data:
    name: caramel-redis-data
  opencode-data:
    name: caramel-opencode-data

networks:
  caramel:
    name: caramel-network
    driver: bridge
